# Generated by Django 4.1.7 on 2023-12-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="url",
            field=models.URLField(default="doesnotwork"),
        ),
    ]
