# Generated by Django 4.1.7 on 2023-12-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_comment_last_edit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.CharField(default="doesnotwork", max_length=200),
        ),
    ]
