# Generated by Django 4.1.7 on 2023-12-13 08:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_subcomments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
