# Generated by Django 4.1.7 on 2023-12-17 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0009_alter_article_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="downvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="total_votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article", name="upvotes", field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ArticleVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_upvote", models.BooleanField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "article")},},
        ),
    ]
