# Generated by Django 4.2.9 on 2024-02-20 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0011_rename_comment_subcomments_parent_comment"),
    ]

    operations = [
        migrations.RenameModel(old_name="Subcomments", new_name="Subcomment",),
    ]
