# Generated by Django 4.2.9 on 2024-02-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_rename_subcomments_subcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcomment",
            name="parent_comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcomments",
                to="mainapp.comment",
            ),
        ),
    ]
