# Generated by Django 4.2.9 on 2024-02-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_alter_subcomment_parent_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="topics",
            field=models.ManyToManyField(to="mainapp.topic"),
        ),
    ]
