# Generated by Django 4.2.9 on 2024-02-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0014_topic_article_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="topics",
            field=models.ManyToManyField(blank=True, to="mainapp.topic"),
        ),
    ]
