# Generated by Django 4.2.9 on 2024-02-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0016_alter_article_topics"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="topics",),
        migrations.DeleteModel(name="Topic",),
    ]
