# Generated by Django 4.2.9 on 2024-02-27 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0018_topic_article_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcomment",
            name="article",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.article",
            ),
            preserve_default=False,
        ),
    ]
